apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: wg
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pyowoongi0426@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pyowoongi-com-tls
  namespace: wg
spec:
  secretName: pyowoongi-com-tls
  duration: 2160h # 90일
  renewBefore: 360h # 15일전에 갱신
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.yeskiticket.shop
  dnsNames:
    - server.yeskiticket.shop