# 메트릭 서버(파드의 자원 상황 모니터링 툴) 설치
# kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

# Horizontal Pod Autoscaler
# 컨테이너 자동 확장
# 10분 지나고 나서 부하가 없을시에 자동으로 기본 POD 대수로 돌아옴 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ordersystem-hpa
  namespace: wg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ordersystem-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

# 부하 테스트 스크립트
# kubectl exec -it 파드명 /bin/bash -n 네임스페이스
# while true; do curl -s http://ordersystem-service/product/list; done

# 부하 모니터링
# -w : watch 옵션을 의미
# kubectl get hpa ordersystem-hpa -n wg -w

