apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
  namespace: wg
  labels:
    app: nginx-busybox-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do wget -qO- http://localhost:80; sleep 5; done']
      