apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: wg
spec:
  # node를 통해 직접 접근 가능한 타입
  type: NodePort
  ports:
  - port: 80 # Service port를 의미
    targetPort: 80 # service가 라우팅해줄 대상의 port(여기선 nginx의 80을 의미)
    nodePort: 30544
  # pod의 labels.app 과 service의 selector.app이 일치해야함에 유의
  selector:
    app: my-nginx