# docker 빌드 후 ecr 업로드 및 kubectl apply

name: deploy ordersystem with k8s
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install
      
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET}}
          aws-region: ap-northeast-2

      - name: update cluster information
        run: aws eks update-kubeconfig --region ap-northeast-2 --name 5-team-cluster

      - name: login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker member images to ecr
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: woongi-member
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest \
          -f ./msa/member/Dockerfile ./msa/member
          docker push $REGISTRY/$REPOSITORY:latest

      - name: eks kubectl apply
        run: |
          kubectl apply -f ./msa/member/k8s/member_depl.yml
          kubectl rollout restart deployment member-deployment -n wg


      - name: build and push docker order images to ecr
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: woongi-order
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest \
          -f ./msa/order/Dockerfile ./msa/order
          docker push $REGISTRY/$REPOSITORY:latest

      - name: eks kubectl apply
        run: |
          kubectl apply -f ./msa/order/k8s/order.yml
          kubectl rollout restart deployment order-deployment -n wg


      - name: build and push docker product images to ecr
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: woongi-product
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest \
          -f ./msa/product/Dockerfile ./msa/product
          docker push $REGISTRY/$REPOSITORY:latest

      - name: eks kubectl apply
        run: |
          kubectl apply -f ./msa/product/k8s/product.yml
          kubectl rollout restart deployment product-deployment -n wg